declare module '@rollup/plugin-image'
declare module 'rollup-plugin-babel'
declare module '@modular-css/rollup'
declare module 'rollup-plugin-babel-minify'
declare module 'rollup-plugin-generate-package-json'
declare module 'rollup-plugin-postcss'
declare module 'cors'
